### PR TITLE
Type-o Corrections #2 - Trello

### PR DESCRIPTION
**Pull request by LaszloNA**

### CODE REVIEW

**Comment by SiobhanCait** [comment]
Thank you Laszlo, I've been through and there is just two of the corrections that need looking at again, I unchecked them on Trello, it should be obvious when you look at it what it is ;) thank you!

**Comment by LaszloNA** [comment]
Just done the corrections on those 2 points.

**Comment by SiobhanCait** [comment]
This looks good thank you! Do I need to press merge?

**Comment by kenlt-uk** [comment]
Laszlo should merge in and then check that it deploys correctly on the preview site, once he has checked that the changes are on preview he should let me know so that I can deploy changes to the live website

**Comment by LaszloNA** [comment]
The events page is blank in the preview..I haven't changed anything, which would break the page, this request contains only type-o corrections. Would you mind to check it Ken, please? Also for merging I would need an approval of my request from you Siobhan.

**Comment by SiobhanCait** [comment]
> The events page is blank in the preview..I haven't changed anything, which would break the page, this request contains only type-o corrections. Would you mind to check it Ken, please? Also for merging I would need an approval of my request from you Siobhan.

Thank you Laszlo, I don't know how to give you approval, what do I need to press? I don't see anything.

**Comment by kenlt-uk** [comment]
Heroku preview only show content changes, it doesn't have any connections with the API which you only get when you merge the PR in and visit the preview website.

**Review by SiobhanCait — APPROVED** [review]

**Pull request merged**
